export const groupOptions = [
  {label: 'Durhams Demographic Numbers', value: 'democount'},
  {label: 'Durhams Demogrphic Percentages', value: 'demopercent'},
  {label: 'Percent Change in Durhams Demographics', value: 'pcdemo'},
  {label: 'Durhams Housing Numbers', value: 'realcount'},
  {label: 'Durhams Housing Percentages', value: 'realpercent'},
  {label: 'Durhams Housing Values', value: 'realvalue'},
  {label: 'Change in Durhams Housing Values', value: 'crealvalue'},
  {label: 'Percent Change in Durhams Housing Values', value: 'pcrealvalue'},
  {label: 'Durhams Housing Sales', value: 'realsale'},
  {label: 'Cost of Rent and Morgage as Percent of Houshold Income', value: 'realcost'},
  {label: 'Change in Durhams Housing Sales', value: 'crealsale'},
  {label: 'Percent Change in Durhams Housing Sales', value: 'pcrealsale'},
  {label: 'Incomes in Durham', value: 'income'},
  {label: 'Change in Durhams Incomes', value: 'cincome'},
  {label: 'Percent Change in Durhams Incomes', value: 'pcincome'},
  {label: 'Durhams Price Income Ratio', value: 'pir'},
  {label: 'Education in Durham', value: 'education'},
  {label: 'Employment in Durham', value: 'employment'}
]
