function setOptions () {
  var options
  if (this.selectgroup.value === 'democount') {
    options = [{label: 'Total Population in 1970', value: 'pop70', unit: '#', type: 'trts'},
      {label: 'Total White Population in 1970', value: 'nhwht70', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 1970', value: 'nhblk70', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 1970', value: 'asian70', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 1970', value: 'haw70', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 1970', value: 'ag25up70', unit: '#', type: 'trts'},
      {label: 'Total Population in 1980', value: 'pop80', unit: '#', type: 'trts'},
      {label: 'Total White Population in 1980', value: 'nhwht80', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 1980', value: 'nhblk80', unit: '#', type: 'trts'},
      {label: 'Total Native Population in 1980', value: 'ntv80', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 1980', value: 'asian80', unit: '#', type: 'trts'},
      {label: 'Total Hispanic Population in 1980', value: 'hisp80', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 1980', value: 'haw80', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 1980', value: 'ag25up80', unit: '#', type: 'trts'},
      {label: 'Total Population in 1990', value: 'pop90', unit: '#', type: 'trts'},
      {label: 'Total White Population in 1990', value: 'nhwht90', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 1990', value: 'nhblk90', unit: '#', type: 'trts'},
      {label: 'Total Native Population in 1990', value: 'ntv90', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 1990', value: 'asian90', unit: '#', type: 'trts'},
      {label: 'Total Hispanic Population in 1990', value: 'hisp90', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 1990', value: 'haw90', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 1990', value: 'ag25up90', unit: '#', type: 'trts'},
      {label: 'Total Population in 2000', value: 'pop00', unit: '#', type: 'trts'},
      {label: 'Total White Population in 2000', value: 'nhwht00', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 2000', value: 'nhblk00', unit: '#', type: 'trts'},
      {label: 'Total Native Population in 2000', value: 'ntv00', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 2000', value: 'asian00', unit: '#', type: 'trts'},
      {label: 'Total Hispanic Population in 2000', value: 'hisp00', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 2000', value: 'haw00', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 2000', value: 'ag25up00', unit: '#', type: 'trts'},
      {label: 'Total Population in 2010', value: 'pop10', unit: '#', type: 'trts'},
      {label: 'Total White Population in 2010', value: 'nhwht10', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 2010', value: 'nhblk10', unit: '#', type: 'trts'},
      {label: 'Total Native Population in 2010', value: 'ntv10', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 2010', value: 'asian10', unit: '#', type: 'trts'},
      {label: 'Total Hispanic Population in 2010', value: 'hisp10', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 2010', value: 'haw10', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 2012', value: 'ag25up12', unit: '#', type: 'trts'},
      {label: 'Total Population in 2016', value: 'pop16', unit: '#', type: 'trts'},
      {label: 'Total White Population in 2016', value: 'nhwht16', unit: '#', type: 'trts'},
      {label: 'Total Black Population in 2016', value: 'nhblk16', unit: '#', type: 'trts'},
      {label: 'Total Native Population in 2016', value: 'ntv16', unit: '#', type: 'trts'},
      {label: 'Total Asian Population in 2016', value: 'asian16', unit: '#', type: 'trts'},
      {label: 'Total Hawaiian Population in 2016', value: 'haw16', unit: '#', type: 'trts'},
      {label: 'Total Other Population in 2016', value: 'oth16', unit: '#', type: 'trts'},
      {label: 'Total Two or More Races Population in 2016', value: 'twomr16', unit: '#', type: 'trts'},
      {label: 'Total Hispanic Population in 2016', value: 'hisp16', unit: '#', type: 'trts'},
      {label: 'Age 25 and Older in 2016', value: 'ag25up16', unit: '#', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'demopercent') {
    options = [{label: 'Percent White Population in 1970', value: 'pnhwht70', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 1970', value: 'pnhblk70', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 1970', value: 'pasian70', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 1970', value: 'phaw70', unit: '%', type: 'trts'},
      {label: 'Percent White Population in 1980', value: 'pnhwht80', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 1980', value: 'pnhblk80', unit: '%', type: 'trts'},
      {label: 'Percent Native Population in 1980', value: 'pntv80', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 1980', value: 'pasian80', unit: '%', type: 'trts'},
      {label: 'Percent Hispanic Population in 1980', value: 'phisp80', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 1980', value: 'phaw80', unit: '%', type: 'trts'},
      {label: 'Percent White Population in 1990', value: 'pnhwht90', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 1990', value: 'pnhblk90', unit: '%', type: 'trts'},
      {label: 'Percent Native Population in 1990', value: 'pntv90', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 1990', value: 'pasian90', unit: '%', type: 'trts'},
      {label: 'Percent Hispanic Population in 1990', value: 'phisp90', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 1990', value: 'phaw90', unit: '%', type: 'trts'},
      {label: 'Percent White Population in 2000', value: 'pnhwht00', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 2000', value: 'pnhblk00', unit: '%', type: 'trts'},
      {label: 'Percent Native Population in 2000', value: 'pntv00', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 2000', value: 'pasian00', unit: '%', type: 'trts'},
      {label: 'Percent Hispanic Population in 2000', value: 'phisp00', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 2000', value: 'phaw00', unit: '%', type: 'trts'},
      {label: 'Percent White Population in 2010', value: 'pnhwht10', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 2010', value: 'pnhblk10', unit: '%', type: 'trts'},
      {label: 'Percent Native Population in 2010', value: 'pntv10', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 2010', value: 'pasian10', unit: '%', type: 'trts'},
      {label: 'Percent Hispanic Population in 2010', value: 'phisp10', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 2010', value: 'phaw10', unit: '%', type: 'trts'},
      {label: 'Percent White Population in 2016', value: 'pnhwht16', unit: '%', type: 'trts'},
      {label: 'Percent Black Population in 2016', value: 'pnhblk16', unit: '%', type: 'trts'},
      {label: 'Percent Native Population in 2016', value: 'pntv16', unit: '%', type: 'trts'},
      {label: 'Percent Asian Population in 2016', value: 'pasian16', unit: '%', type: 'trts'},
      {label: 'Percent Hawaiian Population in 2016', value: 'phaw16', unit: '%', type: 'trts'},
      {label: 'Percent Other Population in 2016', value: 'poth16', unit: '%', type: 'trts'},
      {label: 'Percent Two or More Races Population in 2016', value: 'ptwomr16', unit: '%', type: 'trts'},
      {label: 'Percent Hispanic Population in 2016', value: 'phisp16', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'pcdemo') {
    options = [{label: 'Percent Change in White Population between 2000 and 2010', value: 'pcnhwht0010', unit: '%', type: 'trts'},
      {label: 'Percent Change in Black Population between 2000 and 2010', value: 'pcnhblk0010', unit: '%', type: 'trts'},
      {label: 'Percent Change in Asian Population between 2000 and 2010', value: 'pcasian0010', unit: '%', type: 'trts'},
      {label: 'Percent Change in Hispanic Population between 2000 and 2010', value: 'pchisp0010', unit: '%', type: 'trts'},
      {label: 'Percent Change in White Population between 2000 and 2016', value: 'pcnhwht0016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Black Population between 2000 and 2016', value: 'pcnhblk0016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Asian Population between 2000 and 2016', value: 'pcasian0016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Hispanic Population between 2000 and 2016', value: 'pchisp0016', unit: '%', type: 'trts'},
      {label: 'Percent Change in White Population between 2010 and 2016', value: 'pcnhwht1016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Black Population between 2010 and 2016', value: 'pcnhblk1016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Asian Population between 2010 and 2016', value: 'pcasian1016', unit: '%', type: 'trts'},
      {label: 'Percent Change in Hispanic Population between 2010 and 2016', value: 'pchisp1016', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'realcount') {
    options = [{label: 'Total Housing Units in 1970', value: 'hu70', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 1970', value: 'vac70', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 1970', value: 'ohu70', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 1970', value: 'own70', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 1970', value: 'rent70', unit: '#', type: 'trts'},
      {label: 'Total Housing Units in 1980', value: 'hu80', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 1980', value: 'vac80', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 1980', value: 'ohu80', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 1980', value: 'own80', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 1980', value: 'rent80', unit: '#', type: 'trts'},
      {label: 'Total Housing Units in 1990', value: 'hu90', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 1990', value: 'vac90', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 1990', value: 'ohu90', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 1990', value: 'own90', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 1990', value: 'rent90', unit: '#', type: 'trts'},
      {label: 'Total Housing Units in 2000', value: 'hu00', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 2000', value: 'vac00', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 2000', value: 'ohu00', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 2000', value: 'own00', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 2000', value: 'rent00', unit: '#', type: 'trts'},
      {label: 'Total Housing Units in 2010', value: 'hu10', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 2010', value: 'vac10', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 2010', value: 'ohu10', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 2010', value: 'own10', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 2010', value: 'rent10', unit: '#', type: 'trts'},
      {label: 'Total Housing Units in 2016', value: 'hu16', unit: '#', type: 'trts'},
      {label: 'Total Occupied Housing in 2016', value: 'ohu16', unit: '#', type: 'trts'},
      {label: 'Total Vacant Housing in 2016', value: 'vac16', unit: '#', type: 'trts'},
      {label: 'Total Owner Occupied Housing in 2016', value: 'own16', unit: '#', type: 'trts'},
      {label: 'Total Rental Housing in 2016', value: 'rent16', unit: '#', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'realpercent') {
    options = [{label: 'Percent Vacant Housing in 1970', value: 'pvac70', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 1970', value: 'pohu70', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 1970', value: 'pown70', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 1970', value: 'prent70', unit: '%', type: 'trts'},
      {label: 'Percent Vacant Housing in 1980', value: 'pvac80', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 1980', value: 'pohu80', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 1980', value: 'pown80', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 1980', value: 'prent80', unit: '%', type: 'trts'},
      {label: 'Percent Vacant Housing in 1990', value: 'pvac90', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 1990', value: 'pohu90', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 1990', value: 'pown90', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 1990', value: 'prent90', unit: '%', type: 'trts'},
      {label: 'Percent Vacant Housing in 2000', value: 'pvac00', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 2000', value: 'pohu00', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 2000', value: 'pown00', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 2000', value: 'prent00', unit: '%', type: 'trts'},
      {label: 'Percent Vacant Housing in 2010', value: 'pvac10', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 2010', value: 'pohu10', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 2010', value: 'pown10', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 2010', value: 'prent10', unit: '%', type: 'trts'},
      {label: 'Percent Occupied Housing in 2016', value: 'pohu16', unit: '%', type: 'trts'},
      {label: 'Percent Vacant Housing in 2016', value: 'pvac16', unit: '%', type: 'trts'},
      {label: 'Percent Owner Occupied Housing in 2016', value: 'pown16', unit: '%', type: 'trts'},
      {label: 'Percent Rental Housing in 2016', value: 'prent16', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'realvalue') {
    options = [{label: 'Median Home Value in 1970, Adjusted to 2017 Dollars', value: 'mhmval70a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 1970', value: 'mhmval70', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1970', value: 'mrent70', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1970, Adjusted to 2017 Dollars', value: 'mrent70a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 1980', value: 'mhmval80', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 1980, Adjusted to 2017 Dollars', value: 'mhmval80a17', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1980', value: 'mrent80', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1980, Adjusted to 2017 Dollars', value: 'mrent80a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 1990', value: 'mhmval90', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 1990, Adjusted to 2017 Dollars', value: 'mhmval90a17', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1990', value: 'mrent90', unit: '$', type: 'trts'},
      {label: 'Median Rent in 1990, Adjusted to 2017 Dollars', value: 'mrent90a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2000', value: 'mhmval00', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2000, Adjusted to 2017 Dollars', value: 'mhmval00a17', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2000', value: 'mrent00', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2000, Adjusted to 2017 Dollars', value: 'mrent00a17', unit: '$', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 1998 and 2000', value: 'meansp9800', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 1998 and 2000', value: 'minsp9800', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 1998 and 2000', value: 'maxsp9800', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 1998 and 2000', value: 'mediansp9800', unit: '$', type: 'trts'},
      {label: 'Standard Deviation of Sale Price for Single Family Homes between 1998 and 2000', value: 'stddevsp9800', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 1998 and 2000', value: 'totsp9800', unit: '$', type: 'trts'},
      {label: 'Number of Homes Sold between 1998 and 2000', value: 'nums9800', unit: '#', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 1998 and 2000, Adjusted to 2017 Dollars', value: 'meansp9800a17', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 1998 and 2000, Adjusted to 2017 Dollars', value: 'minsp9800a17', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 1998 and 2000, Adjusted to 2017 Dollars', value: 'maxsp9800a17', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 1998 and 2000, Adjusted to 2017 Dollars', value: 'mediansp9800a17', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 1998 and 2000, Adjusted to 2017 Dollars', value: 'totsp9800a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2012', value: 'mhmval12', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2012, Adjusted to 2017 Dollars', value: 'mhmval12a17', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2012', value: 'mrent12', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2012, Adjusted to 2017 Dollars', value: 'mrent12a17', unit: '$', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 2007 and 2009', value: 'meansp0709', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 2007 and 2009', value: 'minsp0709', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 2007 and 2009', value: 'maxsp0709', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 2007 and 2009', value: 'mediansp0709', unit: '$', type: 'trts'},
      {label: 'Standard Deviation of Sale Price for Single Family Homes between 2007 and 2009', value: 'stddevsp0709', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 2007 and 2009', value: 'totsp0709', unit: '$', type: 'trts'},
      {label: 'Number of Homes Sold between 2007 and 2009', value: 'nums0709', unit: '#', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 2007 and 2009, Adjusted to 2017 Dollars', value: 'meansp0709a17', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 2007 and 2009, Adjusted to 2017 Dollars', value: 'minsp0709a17', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 2007 and 2009, Adjusted to 2017 Dollars', value: 'maxsp0709a17', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 2007 and 2009, Adjusted to 2017 Dollars', value: 'mediansp0709a17', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 2007 and 2009, Adjusted to 2017 Dollars', value: 'totsp0709a17', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2016', value: 'mhmval16', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2016', value: 'mrent16', unit: '$', type: 'trts'},
      {label: 'Median Home Value in 2016, Adjusted to 2017 Dollars', value: 'mhmval16a17', unit: '$', type: 'trts'},
      {label: 'Median Rent in 2016, Adjusted to 2017 Dollars', value: 'mrent16a17', unit: '$', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 2015 and 2017', value: 'meansp1517', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 2015 and 2017', value: 'minsp1517', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 2015 and 2017', value: 'maxsp1517', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 2015 and 2017', value: 'mediansp1517', unit: '$', type: 'trts'},
      {label: 'Standard Deviation of Sale Price for Single Family Homes between 2015 and 2017', value: 'stddevsp1517', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 2015 and 2017', value: 'totsp1517', unit: '$', type: 'trts'},
      {label: 'Number of Homes Sold between 2015 and 2017', value: 'nums1517', unit: '#', type: 'trts'},
      {label: 'Mean Sale Price of Single Family Homes between 2015 and 2017, Adjusted to 2017 Dollars', value: 'meansp1517a17', unit: '$', type: 'trts'},
      {label: 'Minimum Sale Price of Single Family Homes between 2015 and 2017, Adjusted to 2017 Dollars', value: 'minsp1517a17', unit: '$', type: 'trts'},
      {label: 'Maximum Sale Price of Single Family Homes between 2015 and 2017, Adjusted to 2017 Dollars', value: 'maxsp1517a17', unit: '$', type: 'trts'},
      {label: 'Median Sale Price of Single Family Homes between 2015 and 2017, Adjusted to 2017 Dollars', value: 'mediansp1517a17', unit: '$', type: 'trts'},
      {label: 'Total Sale Price of Single Family Homes between 2015 and 2017, Adjusted to 2017 Dollars', value: 'totsp1517a17', unit: '$', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'crealvalue') {
    options = [{label: 'Change in Median Home Value between 2000 and 2012, Adjusted to 2017 Dollars', value: 'cmhmval0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Rent between 2000 and 2012, Adjusted to 2017 Dollars', value: 'cmrent0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Mean Sale Price for Single Family Homes between 2000 and 2009, Adjusted to 2017 Dollars', value: 'cmeansp0009a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Sale Price for Single Family Homes between 2000 and 2009, Adjusted to 2017 Dollars', value: 'cmediansp0009a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Home Value between 2000 and 2016, Adjusted to 2017 Dollars', value: 'cmhmval0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Rent between 2000 and 2016, Adjusted to 2017 Dollars', value: 'cmrent0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Home Value between 2012 and 2016, Adjusted to 2017 Dollars', value: 'cmhmval1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Rent between 2012 and 2016, Adjusted to 2017 Dollars', value: 'cmrent1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Mean Sale Price for Single Family Homes between 2009 and 2017, Adjusted to 2017 Dollars', value: 'cmeansp0917a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Sale Price for Single Family Homes between 2009 and 2017, Adjusted to 2017 Dollars', value: 'cmediansp0917a17', unit: '$', type: 'trts'},
      {label: 'Change in Mean Sale Price for Single Family Homes between 2000 and 2017, Adjusted to 2017 Dollars', value: 'cmeansp0017a17', unit: '$', type: 'trts'},
      {label: 'Change in Median Sale Price for Single Family Homes between 2000 and 2017, Adjusted to 2017 Dollars', value: 'cmediansp0017a17', unit: '$', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'pcrealvalue') {
    options = [{label: 'Percent Change in Median Home Value between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pcmhmval0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Median Rent between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pcmrent0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Median Home Value between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pcmhmval0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Median Rent between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pcmrent0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Median Home Value between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pcmhmval1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Median Rent between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pcmrent1216a17', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'income') {
    options = [{label: 'Median Household Income in 1970', value: 'hinc70', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 1970, Adjusted to 2017 Dollars', value: 'hinc70a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 1980', value: 'hinc80', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 1980, Adjusted to 2017 Dollars', value: 'hinc80a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 1980', value: 'hincw80', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 1980, Adjusted to 2017 Dollars', value: 'hincw80a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 1980', value: 'hincb80', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 1980, Adjusted to 2017 Dollars', value: 'hincb80a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 1980', value: 'hinch80', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 1980, Adjusted to 2017 Dollars', value: 'hinch80a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 1980', value: 'hinca80', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 1980, Adjusted to 2017 Dollars', value: 'hinca80a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 1990', value: 'hinc90', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 1990, Adjusted to 2017 Dollars', value: 'hinc90a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 1990', value: 'hincw90', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 1990, Adjusted to 2017 Dollars', value: 'hincw90a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 1990', value: 'hincb90', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 1990, Adjusted to 2017 Dollars', value: 'hincb90a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 1990', value: 'hinch90', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 1990, Adjusted to 2017 Dollars', value: 'hinch90a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 1990', value: 'hinca90', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 1990, Adjusted to 2017 Dollars', value: 'hinca90a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2000', value: 'hinc00', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2000, Adjusted to 2017 Dollars', value: 'hinc00a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2000', value: 'hincw00', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2000, Adjusted to 2017 Dollars', value: 'hincw00a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2000', value: 'hincb00', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2000, Adjusted to 2017 Dollars', value: 'hincb00a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2000', value: 'hinch00', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2000, Adjusted to 2017 Dollars', value: 'hinch00a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2000', value: 'hinca00', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2000, Adjusted to 2017 Dollars', value: 'hinca00a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2012', value: 'hinc12', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2012, Adjusted to 2017 Dollars', value: 'hinc12a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2012', value: 'hincw12', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2012, Adjusted to 2017 Dollars', value: 'hincw12a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2012', value: 'hincb12', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2012, Adjusted to 2017 Dollars', value: 'hincb12a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2012', value: 'hinch12', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2012, Adjusted to 2017 Dollars', value: 'hinch12a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2012', value: 'hinca12', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2012, Adjusted to 2017 Dollars', value: 'hinca12a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2016', value: 'hinc16', unit: '$', type: 'trts'},
      {label: 'Median Household Income in 2016, Adjusted to 2017 Dollars', value: 'hinc16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2016', value: 'hincw16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Whites in 2016, Adjusted to 2017 Dollars', value: 'hincw16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2016', value: 'hincb16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Blacks in 2016, Adjusted to 2017 Dollars', value: 'hincb16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Natives in 2016', value: 'hincn16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Natives in 2016, Adjusted to 2017 Dollars', value: 'hincn16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2016', value: 'hinca16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Asians in 2016, Adjusted to 2017 Dollars', value: 'hinca16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hawaiians in 2016', value: 'hincp16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hawaiians in 2016, Adjusted to 2017 Dollars', value: 'hincp16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Other in 2016', value: 'hinco16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Other in 2016, Adjusted to 2017 Dollars', value: 'hinco16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Two or More Races in 2016', value: 'hincm16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Two or More Races in 2016, Adjusted to 2017 Dollars', value: 'hincm16a17', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2016', value: 'hinch16', unit: '$', type: 'trts'},
      {label: 'Median Household Income for Hispanics in 2016, Adjusted to 2017 Dollars', value: 'hinch16a17', unit: '$', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'cincome') {
    options = [{label: 'Change in Household Income between 2000 and 2012, Adjusted to 2017 Dollars', value: 'chinc0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for White Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'chincw0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Black Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'chincb0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Asian Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'chinca0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Hispanic Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'chinch0012a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income between 2012 and 2016, Adjusted to 2017 Dollars', value: 'chinc1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for White Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'chincw1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Black Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'chincb1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Asian Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'chinca1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Hispanic Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'chinch1216a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income between 2000 and 2016, Adjusted to 2017 Dollars', value: 'chinc0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for White Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'chincw0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Black Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'chincb0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Asian Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'chinca0016a17', unit: '$', type: 'trts'},
      {label: 'Change in Household Income for Hispanic Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'chinch0016a17', unit: '$', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'pcincome') {
    options = [{label: 'Percent Change in Household Income between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pchinc0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for White Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pchincw0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Black Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pchincb0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Asian Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pchinca0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Hispanic Population between 2000 and 2012, Adjusted to 2017 Dollars', value: 'pchinch0012a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pchinc1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for White Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pchincw1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Black Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pchincb1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Asian Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pchinca1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Hispanic Population between 2012 and 2016, Adjusted to 2017 Dollars', value: 'pchinch1216a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pchinc0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for White Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pchincw0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Black Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pchincb0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Asian Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pchinca0016a17', unit: '%', type: 'trts'},
      {label: 'Percent Change in Household Income for Hispanic Population between 2000 and 2016, Adjusted to 2017 Dollars', value: 'pchinch0016a17', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'pir') {
    options = [{label: 'Price Income Ratio between 1998 and 2000', value: 'pir9800', unit: '\u0020', type: 'trts'},
      {label: 'Price Income Ratio between 2007 and 2012', value: 'pir0712', unit: '\u0020', type: 'trts'},
      {label: 'Price Income Ratio between 2015 and 2017', value: 'pir1517', unit: '\u0020', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'education') {
    options = [{label: 'Number of High School Graduates in 1970', value: 'hs70', unit: '#', type: 'trts'},
      {label: 'Percent High School Graduates in 1970', value: 'phs70', unit: '%', type: 'trts'},
      {label: 'Number of College Graduates in 1970', value: 'col70', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 1970', value: 'pcol70', unit: '%', type: 'trts'},
      {label: 'Number of High School Graduates in 1980', value: 'hs80', unit: '#', type: 'trts'},
      {label: 'Percent High School Graduates in 1980', value: 'phs80', unit: '%', type: 'trts'},
      {label: 'Number of College Graduates in 1980', value: 'col80', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 1980', value: 'pcol80', unit: '%', type: 'trts'},
      {label: 'Number of High School Graduates in 1990', value: 'hs90', unit: '#', type: 'trts'},
      {label: 'Percent High School Graduates in 1990', value: 'phs90', unit: '%', type: 'trts'},
      {label: 'Number of College Graduates in 1990', value: 'col90', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 1990', value: 'pcol90', unit: '%', type: 'trts'},
      {label: 'Number of High School Graduates in 2000', value: 'hs00', unit: '#', type: 'trts'},
      {label: 'Percent High School Graduates in 2000', value: 'phs00', unit: '%', type: 'trts'},
      {label: 'Number of College Graduates in 2000', value: 'col00', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 2000', value: 'pcol00', unit: '%', type: 'trts'},
      {label: 'Number of High School Graduates in 2012', value: 'hs12', unit: '#', type: 'trts'},
      {label: 'Percent High School Graduates in 2012', value: 'phs12', unit: '%', type: 'trts'},
      {label: 'Number of College Graduates in 2012', value: 'col12', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 2012', value: 'pcol12', unit: '%', type: 'trts'},
      {label: 'Percent Change in College Graduates between 2000 and 2012', value: 'pccol0012', unit: '%', type: 'trts'},
      {label: 'Number of Males with Bachelor Degrees in 2016', value: 'batm16', unit: '#', type: 'trts'},
      {label: 'Number of Males with Mater Degrees in 2016', value: 'masm16', unit: '#', type: 'trts'},
      {label: 'Number of Males with Professional Degrees in 2016', value: 'prom16', unit: '#', type: 'trts'},
      {label: 'Number of Males with a PhD in 2016', value: 'phdm16', unit: '#', type: 'trts'},
      {label: 'Number of Females with Bachelor Degrees in 2016', value: 'batf16', unit: '#', type: 'trts'},
      {label: 'Number of Females with Master Degrees in 2016', value: 'masf16', unit: '#', type: 'trts'},
      {label: 'Number of Females with Professional Degrees in 2016', value: 'prof16', unit: '#', type: 'trts'},
      {label: 'Number of Females with a PhD in 2016', value: 'phdf16', unit: '#', type: 'trts'},
      {label: 'Number of College Graduates in 2016', value: 'col16', unit: '#', type: 'trts'},
      {label: 'Percent College Graduates in 2016', value: 'pcol16', unit: '%', type: 'trts'},
      {label: 'Percent Change in College Graduates between 2012 and 2016', value: 'pccol1216', unit: '%', type: 'trts'},
      {label: 'Percent Change in College Graduates between 2000 and 2016', value: 'pccol0016', unit: '%', type: 'trts'}]
  }
  else if (this.selectgroup.value === 'employment') {
    options = [{label: 'Civilian Labor Force in 1970', value: 'clf70', unit: '#', type: 'trts'},
      {label: 'Number of Unemployed in 1970', value: 'unemp70', unit: '#', type: 'trts'},
      {label: 'Percent Unempolyment in 1970', value: 'punemp70', unit: '%', type: 'trts'},
      {label: 'Civilian Labor Force in 1980', value: 'clf80', unit: '#', type: 'trts'},
      {label: 'Number of Unemployed in 1980', value: 'unemp80', unit: '#', type: 'trts'},
      {label: 'Percent Unempolyment in 1980', value: 'punemp80', unit: '%', type: 'trts'},
      {label: 'Civilian Labor Force in 1990', value: 'clf90', unit: '#', type: 'trts'},
      {label: 'Number of Unemployed in 1990', value: 'unemp90', unit: '#', type: 'trts'},
      {label: 'Percent Unempolyment in 1990', value: 'punemp90', unit: '%', type: 'trts'},
      {label: 'Civilian Labor Force in 2000', value: 'clf00', unit: '#', type: 'trts'},
      {label: 'Number of Unemployed in 2000', value: 'unemp00', unit: '#', type: 'trts'},
      {label: 'Percent Unempolyment in 2000', value: 'punemp00', unit: '%', type: 'trts'},
      {label: 'Civilian Labor Force in 2012', value: 'clf12', unit: '#', type: 'trts'},
      {label: 'Number of Unemployed in 2012', value: 'unemp12', unit: '#', type: 'trts'},
      {label: 'Percent Unempolyment in 2012', value: 'punemp12', unit: '%', type: 'trts'}]
  }
  return options
}

export default setOptions
